POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9zY2FyQG9zY2FyLmNvbSIsImV4cCI6MTc0NjU2MjgxMywidXNlcklkIjoyfQ.b19WCE_M4jppxYp2RFIiML4Xf5t1U7mrnCZSE7LXFl4



