POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9zY2FyQG9zY2FyLmNvbSIsImV4cCI6MTc0NjU1OTY1MSwidXNlcklkIjoyfQ.s48x23enIISZUHT4k8VwX-t_w2J1SymLDLJfeG9mDc



